### ISSUE TITLE
Failed download due to 'deleted file' ?

### ISSUE THREAD

**Issue by dalibort** [csm-aut/csm#35]
trying to download ASR9K-iosxr-px-K9-5.3.3.tar which always ends with:

 Traceback (most recent call last):
File "/usr/local/cisco/csm-3.2.1/csmserver/work_units/download_work_unit.py", line 74, in start
bsd.download(output_file_path, callback=self.progress_listener)
File "/usr/local/cisco/csm-3.2.1/csmserver/bsd_service.py", line 135, in download
raise Exception(exception_message)
Exception

after enabling debugging mode I can see on console json result which includes:
"asd_image_exception":[{"exception_code":"Is_Deleted","exception_message":""}]

which probably id the reason the bsd_service.py raises an exception.  I have no idea why the file is marked as deleted one (althought it is offered in CCO/ASR9k-px/5.3.3 ...).
The same behavior observed with 3.2 version

**Comment by dalibort** [comment]
just tried with current github version. The only difference is that debug mode print these lines:
('Exception Code', u'Is_Deleted')
('Exception Message', u'')

**Comment by csm-aut** [comment]
I found the problem.  It has to do with the filename, ASR9K-iosxr-px-K9-5.3.3.tar.  It should be small 'k' as on CCO.  I will try correct it tomorrow.
