### ISSUE TITLE
"Fpd-upgrade" action

### ISSUE THREAD

**Issue by niktestor** [csm-aut/csm#41]
Hi CSM team, 
I really like your project. 
Are you going to do "FPD-upgrade" action?  Will it be in the near future?

SUMMARY

I can run fpd-upgrade action for ios_xr type of equipment from web interface but I do not see the command "upgrade hw-module fpd all location" on the equipment.
I understand that fpd-upgrade plugin is not yet ready. When you are going to do the plugin?

Thank you!

**Comment by csm-aut** [comment]
Yes, including FPD upgrade action is part of the plan.  Hopefully, it will be in the next release (around March).  Is this for ASR9K?

**Comment by niktestor** [comment]
Thank you for responce. 
Yes, this is for ASR9K.

**Comment by csm-aut** [comment]
It is available in CSM v3.5 to be released the end of Sept 17
