### ISSUE TITLE
form validation error in admin console when ldap libraries are not installed

### ISSUE THREAD

**Issue by joydai** [csm-aut/csm#47]
Without ldap libraries installed, whenever save button is clicked in admin console, you get:
NOTICE:  The form has validation errors. Please fix them before saving.

admin_console_form.errors is {'ldap_default_user_privilege': [u'Not a valid choice']} 

Need to confirm action on this issue.

**Comment by csm-aut** [comment]
Fixed the issue by removing the field during validation.
