### ISSUE TITLE
CCO download to select server directory could freeze GUI

### ISSUE THREAD

**Issue by jamesjwei** [csm-aut/csm#63]
Steps to reproduce:

1. CCO Download ASR9K-PX 6.1.2 SMU
2. Click on Action then Download to Server Repository
3. Choose Server Repository (TFTP in this case)
4. In Server Directory, step into sub-directory first then click on the red 'X'.
5. A new pop-op window asks 'Reset the server directory to use the server repository base directory?'
6. Click 'OK' then the web GUI freezes

**Comment by csm-aut** [comment]
Resolved.
