### ISSUE TITLE
Unable to use CSM for NCS6K platform as it uses eXR packaging

### ISSUE THREAD

**Issue by suprp** [csm-aut/csm#88]
Hi,

I was trying to upgrade the NCS6K router using CSM today and it gave me the following error 👍 ERROR:[Install Activate] Abort: Software package earlier than release 5.2.5 for NCS6K is not supported.

The router actually had 631.27I as active package.
RP/0/RP0/CPU0:ios#sh install act summary 
    Active Packages: 1
        ncs6k-xr-6.3.1.27I version=6.3.1.27I [Boot image]

On checking with Prasad, got to know that CSM support for eXR is not present. Can you please add  this enhancment

**Comment by csm-aut** [comment]
Fixed in 3.5
